// apps/cli/templates/auth/convex-auth/web/svelte/src/routes/login/+page.svelte
<script>
  import SignInForm from "$components/SignInForm.svelte";
</script>

<div class="container flex items-center justify-center min-h-[calc(100vh-4rem)] py-8">
  <div class="w-full max-w-md space-y-4">
    <SignInForm />
    <p class="text-center text-sm text-muted-foreground">
      Don't have an account?
      <a href="/signup" class="underline underline-offset-4 hover:text-primary">
        Sign up
      </a>
    </p>
  </div>
</div>

// apps/cli/templates/auth/convex-auth/web/next/src/app/login/page.tsx
import { SignInForm } from "@/components/sign-in-form";
import Link from "next/link";

export default function LoginPage() {
  return (
    <div className="container flex items-center justify-center min-h-[calc(100vh-4rem)] py-8">
      <div className="w-full max-w-md space-y-4">
        <SignInForm />
        <p className="text-center text-sm text-muted-foreground">
          Don't have an account?{" "}
          <Link href="/signup" className="underline underline-offset-4 hover:text-primary">
            Sign up
          </Link>
        </p>
      </div>
    </div>
  );
}
