// apps/cli/templates/auth/convex-auth/web/react/components/user-menu.tsx
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useAuth } from "@/lib/auth-client";
import { Loader2, User } from "lucide-react";

export function UserMenu() {
  const { user, signOut, isLoading } = useAuth();

  if (isLoading) {
    return <Loader2 className="h-4 w-4 animate-spin" />;
  }

  if (!user) {
    return null;
  }

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon">
          <User className="h-4 w-4" />
          <span className="sr-only">User menu</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuLabel>My Account</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem asChild>
          <button
            onClick={() => signOut()}
            className="w-full cursor-pointer"
          >
            Sign out
          </button>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

// apps/cli/templates/auth/convex-auth/web/svelte/src/components/UserMenu.svelte
<script lang="ts">
  import { useAuth } from "$lib/auth-client";
  import { User } from "lucide-svelte";
  
  const { user, signOut, isLoading } = useAuth();
</script>

{#if isLoading}
  <div class="animate-spin h-4 w-4 border-2 border-current border-t-transparent rounded-full" />
{:else if $user}
  <div class="dropdown dropdown-end">
    <button class="btn btn-ghost btn-circle" tabindex="0">
      <User size={16} />
      <span class="sr-only">User menu</span>
    </button>
    <ul class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
      <li class="menu-title">My Account</li>
      <li>
        <button on:click={() => signOut()}>
          Sign out
        </button>
      </li>
    </ul>
  </div>
{/if}
